name: postman collection workflow

on:
  push:
    branches: [main]
  workflow_dispatch:   # allows manual trigger
  schedule:            # cron-based triggers
    - cron: '30 20 * * *'   # 8 am IST every day
    - cron: '00 14 * * *'   # 7:30 pm IST every day
    - cron: '00 06 * * 1-5' # 11:30 am IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Newman and Html-extra globally
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection with Newman
        run: |
          newman run "Inwarranty-Flow-Request Copy.postman_collection.json" \
          -e "QA INT.postman_environment.json" \
          -d "textdata.csv" \
          -r cli,htmlextra \
          --reporter-htmlextra-export newman/report.html

      - name: Upload Newman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/*.html

      - name: Deploy Newman Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman
