name: postman collection workflow

on:
  push:
    branches: [main]
  workflow_dispatch:   # allows manual trigger
  schedule:            # cron-based triggers
    - cron: '30 20 * * *'   # 8 am IST every day
    - cron: '00 14 * * *'   # 7:30 pm IST every day
    - cron: '00 06 * * 1-5' # 11:30 am IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu runner

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Newman and Html-extra globally
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection with Newman
        run: |
          newman run "Inwarranty-Flow-Request Copy.postman_collection.json" \
          -e "QA INT.postman_environment.json" \
          -d "textdata.csv" \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html

      - name: Newman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/*.html

      - name: Deploy Newman Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v9
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMIAL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: Phoenix inwarrenty flow test execution flow 
            to: shridharsapkal2026@gmail.com
            from: ${{ secrets.EMIAL_USERNAME }}
            body: 
                 Hi,
                 Phoenix inwarrenty flow is executed and report is published and URL is- https://shridharsapkal1996-cell.github.io/Phoeniex-Inwarrnty-flow/
            attachments: newman/index.html
            
        
      
